Tricorder-RaspberryPi: serial_manager Namespace Reference
serial_manager Namespace Reference
Functions for serial comminication with MCU.
Functions
def get_battery ()
Get battery voltage & percentage from Adafruit fuel gauge.
def get_gps ()
Read data from GPS sensor.
def get_imu_acc ()
BNO055 IMU: get x/y/z axes overall acceleration.
def get_imu_ang_vel ()
BNO055 IMU: get x/y/z axes angular velocity.
def get_imu_grav ()
BNO055 IMU: get x/y/z axes readings for adjusted gravitational acceleration.
def get_imu_lin_acc ()
BNO055 IMU: get x/y/z axes linear acceleration.
def get_imu_mag ()
BNO055 IMU: get x/y/z axes magnetic field strength.
def get_imu_orientation ()
BNO055 IMU: get heading, roll, pitch.
def get_multimeter ()
Get readings from current sensor INA219.
def get_noise ()
Get analog value from electret microphone.
def get_pm25 ()
Get particulate matter readings.
def get_pressure ()
Get barometric pressure, temperature, and est altitude readings.
def get_radiation ()
Read analog value from geiger counter module.
def get_serial_vals (send_msg, dict_names_list)
Main function actually responsible for serial communication msg send/recv.
def get_spectrometer ()
Get readings from photo spectrometer.
def get_temp_humid ()
Get temperature and humidity readings.
def get_tvoc_eco2 ()
Get volatile organic compound and estimated CO2 readings.
def get_uv ()
Get readings from UV light sensor.
def get_vis_ir ()
Get readings for visible and infrared light.
def get_wind ()
Read analog value from wind sensor.
def my_flush ()
Dump serial vals.
def set_geiger_power_off ()
Disconnect power to geiger counter module by switching assigned mosfet.
def set_geiger_power_on ()
Reconnect power to geiger counter module by switching assigned mosfet.
def set_pm25_power_off ()
Disconnect power to PM25 sensor by switching assigned mosfet.
def set_pm25_power_on ()
Reconnect power to PM25 sensor by switching assigned mosfet.
def set_tsl_gain (new_gain)
Set gain of TSL2591 vis/ir sensor.
def set_tsl_scl_connect ()
Reconnect the SCL signal for TSL2591 vis/ir sensor.
def set_tsl_scl_disconnect ()
Disconnect the SCL signal for TSL2591 vis/ir sensor.
Variables
string PORT_NAME = "/dev/my_esp32"
This is the custom assigned port for esp32.
ser
Serial communication object.
Detailed Description
Functions for serial comminication with MCU.
This file contains functions for communicating over a serial usb/bluetooth link using tcp/ip sockets.
    -> Each sensor page can import relevant functions for efficiency.
    -> Keeping all in one place in case of changes to how I communicate with sensors.
By sending data back and forth:
    -> Data can be requested from sensors
    -> Sensor-specific settings can be changed
    -> Microcontroller operations can be changed (e.g., sleep mode)
    -> Both of the above involves sending specific mappings from mappings.py
Function Documentation
get_battery()
def serial_manager.get_battery ()
Get battery voltage & percentage from Adafruit fuel gauge.
    Dictionary keys:
        ['volt', 'pct', 'temp']
Returns
if normal -> voltage, battery pct, battery temperature
if error -> -1, -1, -1
References get_serial_vals().
get_gps()
def serial_manager.get_gps ()
Read data from GPS sensor.
    Dictionary keys:
        ['lat', 'lng', 'alt', 'spd', 'sat']
Returns
if normal -> latitude, longitude, altitude, speed, num satellites
if error -> -1, -1, -1, -1, -1
References get_serial_vals().
Referenced by FlyPage.get_sensor_data(), and GPSSensorPage.update_gps_data().
get_imu_acc()
def serial_manager.get_imu_acc ()
BNO055 IMU: get x/y/z axes overall acceleration.
    Dictionary keys:
        ['X','Y','Z']
Returns
if normal -> x, y, z
if error -> -1, -1, -1
References get_serial_vals().
Referenced by IMUSensorPage.blit_accelerometer().
get_imu_ang_vel()
def serial_manager.get_imu_ang_vel ()
BNO055 IMU: get x/y/z axes angular velocity.
    Dictionary keys:
        ['X','Y','Z']
Returns
if normal -> x, y, z
if error -> -1, -1, -1
References get_serial_vals().
Referenced by IMUSensorPage.blit_angular_velocity().
get_imu_grav()
def serial_manager.get_imu_grav ()
BNO055 IMU: get x/y/z axes readings for adjusted gravitational acceleration.
    Dictionary keys:
        ['X','Y','Z']
Returns
if normal -> x, y, z
if error -> -1, -1, -1
References get_serial_vals().
Referenced by IMUSensorPage.blit_gravity().
get_imu_lin_acc()
def serial_manager.get_imu_lin_acc ()
BNO055 IMU: get x/y/z axes linear acceleration.
    Dictionary keys:
        ['X','Y','Z']
Returns
if normal -> x, y, z
if error -> -1, -1, -1
References get_serial_vals().
Referenced by IMUSensorPage.blit_linear_acc().
get_imu_mag()
def serial_manager.get_imu_mag ()
BNO055 IMU: get x/y/z axes magnetic field strength.
    Dictionary keys:
        ['X','Y','Z']
Returns
if normal -> x, y, z
if error -> -1, -1, -1
References get_serial_vals().
Referenced by IMUSensorPage.blit_magnetometer().
get_imu_orientation()
def serial_manager.get_imu_orientation ()
BNO055 IMU: get heading, roll, pitch.
    Dictionary keys:
        ['Hd','Rl','Ph']
Returns
if normal -> heading, roll, pitch
if error -> -1, -1, -1
References get_serial_vals().
Referenced by IMUSensorPage.blit_orientation(), and FlyPage.get_sensor_data().
get_multimeter()
def serial_manager.get_multimeter ()
Get readings from current sensor INA219.
Warning
This works differently from others.
Returns
if normal -> current, voltage, power
if error -> -1, -1, -1
get_noise()
def serial_manager.get_noise ()
Get analog value from electret microphone.
    Dictionary keys:
        ['noise_out']
Returns
if normal -> noise_out
if error -> 0
References get_serial_vals().
get_pm25()
def serial_manager.get_pm25 ()
Get particulate matter readings.
    Dictionary keys:
        ['03um', '05um', '10um', '25um', '50um', '100um']
Returns
if normal -> [val, val, val, val, val, val]
if error -> [1, 1, 1, 1, 1, 1]
References get_serial_vals().
Referenced by HomePage.display_particulate_matter(), and PM25Page.next_frame().
get_pressure()
def serial_manager.get_pressure ()
Get barometric pressure, temperature, and est altitude readings.
    Dictionary keys:
                ['pressure', 'bmp_temp', 'p_over', 't_over', 'alt']
Returns
if normal -> altitude, pressure, bmp_temp, p_oversampling, t_oversampling
if error -> -1, -1, -1, -1, -1
References get_serial_vals().
Referenced by HomePage.blit_pressure(), FlyPage.get_sensor_data(), and PressureSensorPage.next_frame().
get_radiation()
def serial_manager.get_radiation ()
Read analog value from geiger counter module.
    Dictionary keys:
        ['CPM']
Returns
if normal -> CPM
if error -> -1
References get_serial_vals().
Referenced by GeigerCounterPage.next_frame().
get_serial_vals()
def serial_manager.get_serial_vals (send_msg, dict_names_list)
Main function actually responsible for serial communication msg send/recv.
Parameters
send_msg Message (i.e., code) to be sent.
dict_names_list Sensor specific names for returned name/value pairs.
Returns
Dictionary with name-value pairs specified in dict_names_list.
Note
This is a note
More comment
Referenced by get_battery(), get_gps(), get_imu_acc(), get_imu_ang_vel(), get_imu_grav(), get_imu_lin_acc(), get_imu_mag(), get_imu_orientation(), get_noise(), get_pm25(), get_pressure(), get_radiation(), get_spectrometer(), get_temp_humid(), get_tvoc_eco2(), get_uv(), and get_vis_ir().
get_spectrometer()
def serial_manager.get_spectrometer ()
Get readings from photo spectrometer.
    Dictionary keys:
        ['c_415nm','c_445nm','c_480nm','c_515nm','c_555nm','c_590nm','c_630nm','c_680nm','clear','nir']
Returns
if normal -> {'c_415nm':val, 'c_445nm':val, 'c_480nm':val, 'c_515nm':val, 'c_555nm':val, 'c_590nm':val, 'c_630nm':val, 'c_680nm':val, 'clear':val, 'nir':val}
if error -> {'c_415nm':0,'c_445nm':0,'c_480nm':0,'c_515nm':0,'c_555nm':0,'c_590nm':0,'c_630nm':0,'c_680nm':0,'clear':0,'nir':0}
References get_serial_vals().
Referenced by HomePage.blit_spectrometer(), and SpecPage.next_frame().
get_temp_humid()
def serial_manager.get_temp_humid ()
Get temperature and humidity readings.
    Dictionary keys:
                ['temperature', 'relative_humidity', 'heater', 'h_res', 't_res']
Returns
if normal -> temperature, relative_humidity, h_res, t_res
if error -> -1,-1,-1,-1
References get_serial_vals().
Referenced by HomePage.blit_temp(), and FlyPage.get_sensor_data().
get_tvoc_eco2()
def serial_manager.get_tvoc_eco2 ()
Get volatile organic compound and estimated CO2 readings.
    Dictionary keys:
                ['eCO2', 'TVOC', 'raw_H2', 'raw_ethanol', 'baseline_eCO2', 'baseline_TVOC']
Returns
if normal -> TVOC, eCO2, baseline_eCO2, baseline_TVOC
if error -> -1,-1,-1,-1
References get_serial_vals().
Referenced by HomePage.blit_tvoc_eco2().
get_uv()
def serial_manager.get_uv ()
Get readings from UV light sensor.
    Dictionary keys:
                ['uvs','light','uvi','ltr_lux','ltr_gain','ltr_res','ltr_win_fac','ltr_mdelay']
Returns
if normal -> uvs, light, uvi, ltr_lux, ltr_gain, ltr_resolution, ltr_window_factor, ltr_measurement_delay
if error -> -1, -1, -1, -1, -1, -1, -1, -1
References get_serial_vals().
Referenced by HomePage.blit_uv(), and FlyPage.get_sensor_data().
get_vis_ir()
def serial_manager.get_vis_ir ()
Get readings for visible and infrared light.
    Dictionary keys:
                ['lux', 'infrared', 'visible', 'full_spectrum', 'tsl2591_gain']
Returns
if normal -> lux, ir, gain, visible, full_spectrum
if error -> -1,-1,-1,-1,-1
References get_serial_vals().
Referenced by HomePage.blit_vis_ir(), FlyPage.get_sensor_data(), and LightSensorPage.next_frame().
get_wind()
def serial_manager.get_wind ()
Read analog value from wind sensor.
Warning
This works differently from others.
Returns
if normal -> wind_val
if error -> -1
my_flush()
def serial_manager.my_flush ()
Dump serial vals.
Referenced by SleepPage.wake_from_sleep().
set_geiger_power_off()
def serial_manager.set_geiger_power_off ()
Disconnect power to geiger counter module by switching assigned mosfet.
Referenced by GeigerCounterPage.on_exit().
set_geiger_power_on()
def serial_manager.set_geiger_power_on ()
Reconnect power to geiger counter module by switching assigned mosfet.
Referenced by GeigerCounterPage.on_enter().
set_pm25_power_off()
def serial_manager.set_pm25_power_off ()
Disconnect power to PM25 sensor by switching assigned mosfet.
Referenced by PM25Page.on_exit().
set_pm25_power_on()
def serial_manager.set_pm25_power_on ()
Reconnect power to PM25 sensor by switching assigned mosfet.
Referenced by PM25Page.on_enter().
set_tsl_gain()
def serial_manager.set_tsl_gain (new_gain)
Set gain of TSL2591 vis/ir sensor.
Referenced by LightSensorPage.next_frame().
set_tsl_scl_connect()
def serial_manager.set_tsl_scl_connect ()
Reconnect the SCL signal for TSL2591 vis/ir sensor.
Referenced by FlyPage.get_sensor_data(), and LightSensorPage.on_enter().
set_tsl_scl_disconnect()
def serial_manager.set_tsl_scl_disconnect ()
Disconnect the SCL signal for TSL2591 vis/ir sensor.
Referenced by FlyPage.get_sensor_data(), IMUSensorPage.on_enter(), and LightSensorPage.on_exit().
Variable Documentation
PORT_NAME
string PORT_NAME = "/dev/my_esp32"
This is the custom assigned port for esp32.
ser
ser
Initial value:
 =  serial.Serial(
         port=PORT_NAME, # Change this according to connection methods, e.g. /dev/ttyUSB0
         baudrate = 115200,
         parity=serial.PARITY_NONE,
         stopbits=serial.STOPBITS_ONE,
         bytesize=serial.EIGHTBITS,
         timeout=1
     )
Serial communication object.