Tricorder-RaspberryPi: global_functions Namespace Reference
global_functions Namespace Reference
Contains functions invoked by several different parts of the code.
Functions
def adjust_gauge_lims (curr_val, gauge)
For circular gauges.
def blit_some_stats (screen, width, day, date, hour_sec, fps, cpu_pct, cpu_temp, wifi_name, wifi_symbol, bluetooth_img)
These pieces of info are always displayed in the top bar or in the Okudagrams.
def blitRotate2 (surf, image, topleft, angle)
Rotate an image around its center.
def flip_buttons (pressed_button, button_list)
Unselect all other buttons except the one just pressed.
def get_date_time ()
Get formatted time for top toolbar display.
def get_text_dimensions (text='', font_style=FONT_DIN, font_color=WHITE, style=0, font_size=28)
Return size of to-be-rendered text.
def get_wifi_name ()
Check for connected wifi network.
def my_map (x, in_min, in_max, out_min, out_max)
Standard mapping formula.
def update_cpu_stats (dt=None)
Get rapsberry pi usage stats.
Detailed Description
Contains functions invoked by several different parts of the code.
Function Documentation
adjust_gauge_lims()
def global_functions.adjust_gauge_lims (curr_val, gauge)
For circular gauges.
Adjusts upper/lower limits to nearest round numbers
blit_some_stats()
def global_functions.blit_some_stats (screen, width, day, date, hour_sec, fps, cpu_pct, cpu_temp, wifi_name, wifi_symbol, bluetooth_img)
These pieces of info are always displayed in the top bar or in the Okudagrams.
References get_date_time(), and get_text_dimensions().
Referenced by MenuHomePageClass.animate().
blitRotate2()
def global_functions.blitRotate2 (surf, image, topleft, angle)
Rotate an image around its center.
Referenced by FlyPage.blit_art_horizon().
flip_buttons()
def global_functions.flip_buttons (pressed_button, button_list)
Unselect all other buttons except the one just pressed.
get_date_time()
def global_functions.get_date_time ()
Get formatted time for top toolbar display.
Referenced by MenuHomePageClass.animate(), blit_some_stats(), WindowManager.log_to_file(), and WindowManager.take_screenshot_func().
get_text_dimensions()
def global_functions.get_text_dimensions (text = '', font_style = FONT_DIN, font_color = WHITE, style = 0, font_size = 28)
Return size of to-be-rendered text.
Referenced by UVSensorPage.blit_current_settings(), AA_Gauge.blit_gauge(), blit_some_stats(), DeviceInfoClass.blit_write_count(), PM25Page.info_subpage(), SpecPage.info_subpage(), and sensor_pages.fly_page.txt_dims().
get_wifi_name()
def global_functions.get_wifi_name ()
Check for connected wifi network.
Return network name
Referenced by DeviceInfoClass.update().
my_map()
def global_functions.my_map (x, in_min, in_max, out_min, out_max)
Standard mapping formula.
Used in many places
Referenced by FlyPage.blit_art_horizon(), AA_Gauge.blit_gauge(), GPSSensorPage.draw_location_lines(), SpecPage.scale_rgb(), and SpecPage.scale_rgb2().
update_cpu_stats()
def global_functions.update_cpu_stats (dt = None)
Get rapsberry pi usage stats.
Referenced by DeviceInfoClass.update().