Tricorder-RaspberryPi: sensor_pages.fly_page Namespace Reference
sensor_pages.fly_page Namespace Reference
Mimics the avionics displays used in airplanes Eg: garmin-xxxx.
Classes
class FlyPage
Mimics the avionics displays used in airplanes Eg: garmin-xxxx.
Functions
def blit_column_txt (screen, x_val, curr_val)
Blit text for speed and altitude indicators.
def compute_positions (x_val, curr_val)
Computes positions for icons and text.
def txt_dims (txt)
wrapper function.
Variables
R_ALT
Rect object for altitude indicator.
R_SPD
Rect object for speed indicator.
Detailed Description
Mimics the avionics displays used in airplanes Eg: garmin-xxxx.
Function Documentation
blit_column_txt()
def sensor_pages.fly_page.blit_column_txt (screen, x_val, curr_val)
Blit text for speed and altitude indicators.
References sensor_pages.fly_page.compute_positions().
Referenced by FlyPage.blit_vertical_column().
compute_positions()
def sensor_pages.fly_page.compute_positions (x_val, curr_val)
Computes positions for icons and text.
Referenced by sensor_pages.fly_page.blit_column_txt().
txt_dims()
def sensor_pages.fly_page.txt_dims (txt)
wrapper function.
References global_functions.get_text_dimensions().
Referenced by FlyPage.blit_vertical_column().
Variable Documentation
R_ALT
R_ALT
Initial value:
 = pygame.Rect(ALTITUDE_RECT_X_POS, ALTITUDE_RECT_Y_POS, \
                         ALTITUDE_RECT_WIDTH, ALTITUDE_RECT_HEIGHT)
Rect object for altitude indicator.
R_SPD
R_SPD
Initial value:
 = pygame.Rect(SPEED_RECT_X_POS, SPEED_RECT_Y_POS, \
                         SPEED_RECT_WIDTH, SPEED_RECT_HEIGHT)
Rect object for speed indicator.