Tricorder-RaspberryPi: general_pages.exit_page Namespace Reference
general_pages.exit_page Namespace Reference
Faux page for clean exit.
Classes
class ExitPage
Faux page for clean exit.
Functions
def elapsed_time (print_res=False)
Calculates total runtime from start of program.
def wrap_up ()
Prints a nice goodbye message and elapsed time.
Variables
start_time_overall = time.time()
Detailed Description
Faux page for clean exit.
Function Documentation
elapsed_time()
def general_pages.exit_page.elapsed_time (print_res = False)
Calculates total runtime from start of program.
Referenced by DeviceStatsPage.next_frame(), and general_pages.exit_page.wrap_up().
wrap_up()
def general_pages.exit_page.wrap_up ()
Prints a nice goodbye message and elapsed time.
References general_pages.exit_page.elapsed_time().
Referenced by ExitPage.next_frame().
Variable Documentation
start_time_overall
start_time_overall = time.time()