Tricorder-RaspberryPi: freqshow_code.views Namespace Reference
freqshow_code.views Namespace Reference
FreqShow application views.
Classes
class InstantSpectrogram
Instantaneous point in time line plot of the spectrogram.
class MessageDialog
Dialog which displays a message in the center of the screen with an OK and optional cancel button.
class NumberDialog
Dialog which asks the user to enter a numeric value.
class SettingsList
Setting list view.
class SpectrogramBase
Base class for a spectrogram view.
class ViewBase
Base class for simple UI view which represents all the elements drawn on the screen.
class WaterfallSpectrogram
Scrolling waterfall plot of spectrogram data.
Functions
def clamp (x, x0, x1)
Clamp a provided value to be between x0 and x1 (inclusive).
def gradient_func (colors)
Build a waterfall color function from a list of RGB color tuples.
def lerp (x, x0, x1, y0, y1)
Linear interpolation of value y given min and max y values (y0 and y1), min and max x values (x0 and x1), and x value.
def rgb_lerp (x, x0, x1, c0, c1)
Linear interpolation of RGB color tuple c0 and c1.
Detailed Description
FreqShow application views.
Function Documentation
clamp()
def freqshow_code.views.clamp (x, x0, x1)
Clamp a provided value to be between x0 and x1 (inclusive).
If value is outside the range it will be truncated to the min/max value which is closest.
Referenced by WaterfallSpectrogram.render_spectrogram().
gradient_func()
def freqshow_code.views.gradient_func (colors)
Build a waterfall color function from a list of RGB color tuples.
The returned function will take a numeric value from 0 to 1 and return a color interpolated across the gradient of provided RGB colors.
References freqshow_code.views.rgb_lerp().
lerp()
def freqshow_code.views.lerp (x, x0, x1, y0, y1)
Linear interpolation of value y given min and max y values (y0 and y1), min and max x values (x0 and x1), and x value.
Referenced by freqshow_code.views.rgb_lerp().
rgb_lerp()
def freqshow_code.views.rgb_lerp (x, x0, x1, c0, c1)
Linear interpolation of RGB color tuple c0 and c1.
References freqshow_code.views.lerp().
Referenced by freqshow_code.views.gradient_func().