Tricorder-RaspberryPi: plotting_functions Namespace Reference
plotting_functions Namespace Reference
Contains matplotlib-derived functions used for graphiing.
Functions
def bar_plot (fig, ax, canvas, x_labels, color_list, curr_vals, ylabel='')
Makes bar plot.
def line_plot (fig, ax, canvas, color_list, x_array, array_dict)
Makes line plot for one or more data series.
def pie_plot (fig, ax, canvas, color_list, pie_labels, curr_vals)
Makes pie plot.
def plot2img (fig, ax, canvas)
Converts matplotlib plot to image.
Variables
tuple COLOR = (0.75,0.75,0.75)
Default color for text, axes, and ticks.
Detailed Description
Contains matplotlib-derived functions used for graphiing.
Function Documentation
bar_plot()
def plotting_functions.bar_plot (fig, ax, canvas, x_labels, color_list, curr_vals, ylabel = '')
Makes bar plot.
Parameters
fig Required for converting plot to surface.
ax Matplotlib axis to be used for plotting.
canvas Pygame canvas to be returned as surface.
color_list Colors for different series.
curr_vals Values for making bar plot.
ylabel Y-axis labels.
Returns
Pygame surface with bar plot.
References plot2img().
line_plot()
def plotting_functions.line_plot (fig, ax, canvas, color_list, x_array, array_dict)
Makes line plot for one or more data series.
Parameters
fig Required for converting plot to surface.
ax Matplotlib axis to be used for plotting.
canvas Pygame canvas to be returned as surface.
color_list Colors for different series.
x_array Data to be plotted for a specific series.
array_dict For use with multiple data series.
Returns
Pygame surface with line plot.
References plot2img().
pie_plot()
def plotting_functions.pie_plot (fig, ax, canvas, color_list, pie_labels, curr_vals)
Makes pie plot.
Parameters
fig Required for converting plot to surface.
ax Matplotlib axis to be used for plotting.
canvas Pygame canvas to be returned as surface.
color_list Colors for different series.
pie_labels Labels for each series.
curr_vals Vals for plotting pie chart.
Returns
Pygame surface with pie plot.
References plot2img().
Referenced by HomePage.blit_spectrometer().
plot2img()
def plotting_functions.plot2img (fig, ax, canvas)
Converts matplotlib plot to image.
Sets BG colorkey to BLACK for transparent surface.
Returns
Pygame surface.
Referenced by bar_plot(), line_plot(), BatterySensorPage.make_plot(), GeigerCounterPage.next_frame(), pie_plot(), MultimeterPage.render_generic_graph(), and ThermalCamPage.thermal_plotter().
Variable Documentation
COLOR
tuple COLOR = (0.75,0.75,0.75)
Default color for text, axes, and ticks.